### ISSUE TITLE
Odstrani `__pycache__`

### ISSUE THREAD

**Issue by andrejbauer** [PircK/six#1]
Mapa `__pycache__` ne spada v repozitorij, odstranita jo. Nato dodajta `__pycache__` v `.gitignore`, da ne bo Git ponujal, da ga doda v repozitorij.

**Comment by andrejbauer** [comment]
A ste bili na predavanju? Ko se zapre issue, je treba narediti referenco is commita na issue: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by PircK** [comment]
obupala.

**Comment by andrejbauer** [comment]
He he, čestitke za vztrajnost ;-)
